// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountParams = {
/**
 * When `true`, requests a proactive token refresh before returning.
 *
 * In managed auth mode this triggers the normal refresh-token flow. In
 * external auth mode this flag is ignored. Clients should refresh tokens
 * themselves and call `account/login/start` with `chatgptAuthTokens`.
 */
refreshToken?: boolean,
/**
 * When `true`, reloads the auth snapshot from storage before returning.
 *
 * This keeps long-lived clients in sync with `auth.json` updates without
 * requiring a full app-server restart.
 */
reloadAuthFromStorage?: boolean, };
